controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# yamlroute:
#     path: /yamlroute
#     controller: App\Controller\HomeController::yamlroute
